version: '3.1'

services:

  wordpress:
    container_name: wordpress
    image: wordpress
    ports:
      - 8091:80
    environment:
      WORDPRESS_DB_HOST: wordpressdb
      WORDPRESS_DB_USER: jefferson
      WORDPRESS_DB_PASSWORD: 123
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - wordpress:/var/www/html
      - ./products:/var/www/html/wp-content/plugins/products

  wordpressdb:
    container_name: wordpressdb
    image: mysql:5.7
    ports:
      - 3309:3306
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: jefferson
      MYSQL_PASSWORD: 123
      MYSQL_ROOT_PASSWORD: 123
    volumes:
      - wordpressdb:/var/lib/mysql

volumes:
  wordpress:
  wordpressdb:
